### ISSUE TITLE
Onchain data for distributions

### ISSUE THREAD

**Issue by judezhu** [flow-hydraulics/flow-pds#76]
After discussion, we are requesting to add following data to `distribution` onchain:

```
        pub let title: String.                   # required field 
        pub let metadata: {String: String}.      # optional fields
        pub let state: String                    # state would be: invalid/completed
```

Also update the `DistributionCreated` event:
```
      # Issuer has created a distribution 
       pub event DistributionCreated(id: UInt32, title: String, metadata: {String: String}, state:String)
```

**Comment by judezhu** [comment]
Question: When do we emit `DistributionCreated` event? Does invalid distribution also emit `DistributionCreated` event?

**Comment by whalelephant** [comment]
`DistributionCreated` event is emitted when the user initially creates it. They will then need to use the emitted `distId` to configure the distribution on the backend so the backend knows where to find the capabilities.
